

import Head from 'next/head'


import styles from '@/styles/Dashboard.module.css'
import { NavBar } from '@/components/NavBar'
import { SideBar } from '@/components/SideBar'



export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <header>
          <NavBar />
        </header>
        <main>
          <SideBar />
        </main>
    </>
  )
}
